cc_library(
    name = "ta_func",
    srcs = glob([
        "ta_*.c",
    ]),
    hdrs = [
        "ta_utility.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//include:ta_func_headers",
        "//src/ta_common",
    ],
)
